Repository genropy/genropy, pull requests merged in 2025-05, with the labels that each got.

#177 Avoid StopIteration error when importing empty sheets. Closes #176
  gnrpy/gnr/core/gnrlist.py
Labels: Review effort 1/5

#180 Required columns added to webstruct
  gnrjs/gnr_d11/js/genro_grid.js
  gnrpy/gnr/web/gnrwebstruct.py
Labels: Review effort 2/5

#173 Dbadmin service and package/instance testing infrastructure
  gnrpy/gnr/dev/cli/gnrtests.py
  gnrpy/gnr/dev/packagetester.py
  gnrpy/gnr/lib/services/__init__.py
  projects/gnrcore/packages/sys/lib/services/dbadmin.py
  projects/gnrcore/packages/sys/resources/services/dbadmin/postgres.py
  projects/gnrcore/packages/sys/tests/test_dbadmin_service.py
Labels: Review effort 3/5
